#!/usr/bin/env python3
"""Summarize actual saved native experiments; never infer acceptance from solver status."""
import json
from pathlib import Path
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from native import ROOT, Native
DATA=ROOT/'data/generated/dynamics'
DOC=ROOT/'docs/experiments/milestone-6-dynamics-results.md'
def read(p):return json.loads(p.read_text())
def compact(j):return {k:v for k,v in j.items() if k not in {'samples','commands','evaluations','initial','final','profile','bound_selection_audit','replay_stable_selection_audit'}}
study=[]
for p in sorted((DATA/'study').glob('*.json')):
 j=read(p)
 if isinstance(j,dict) and 'profile' in j:study.append({'name':p.stem,**compact(j)})
(DATA/'study/summary.json').write_text(json.dumps(study,indent=2)+'\n')
def vector(rows,key):return np.array([r[key] for r in rows])
def interp(j,s,key):return np.interp(s,vector(j['samples'],'s'),vector(j['samples'],key))
def details(j,reference):
 a=j['samples'];b=reference['samples'];start=max(a[0]['s'],b[0]['s']);end=min(a[-1]['s'],b[-1]['s']);grid=np.arange(start,end-100,1.)
 gain=(interp(reference,grid+100,'time')-interp(reference,grid,'time'))-(interp(j,grid+100,'time')-interp(j,grid,'time'));idx=int(gain.argmax());delta=np.linspace(start,end,1000)
 return {'reference_lap_time_s':reference['lap_time_s'],'lap_time_s':j['lap_time_s'],'improvement_s':reference['lap_time_s']-j['lap_time_s'],
 'largest_100m_gain':{'start_m':float(grid[idx]),'end_m':float(grid[idx]+100),'gain_s':float(gain[idx])},
 'peak_speed_kph':float(np.linalg.norm(vector(a,'velocity'),axis=1).max()*3.6),
 'peak_abs_lateral_g':float(np.abs(vector(a,'bodyAcceleration')[:,1]).max()/9.80665),
 'peak_braking_g':float(-vector(a,'bodyAcceleration')[:,0].min()/9.80665),
 'peak_downforce_n':float(vector(a,'downforce').max()),'peak_drag_n':float(vector(a,'drag').max()),
 'maximum_offset_difference_m':float(np.max(np.abs(interp(j,delta,'lateral')-interp(reference,delta,'lateral')))),
 'mean_tire_utilization':float(np.mean([w['utilization'] for r in a for w in r['wheels']])),
 'reference_mean_tire_utilization':float(np.mean([w['utilization'] for r in b for w in r['wheels']])),
 'peak_tire_utilization':max(w['utilization'] for r in a for w in r['wheels']),
 'minimum_tire_load_n':min(w['fz'] for r in a for w in r['wheels']),
 'samples_with_any_contact_loss':sum(any(not w['contact'] for w in r['wheels']) for r in a),
 'fuel_kg':j['fuel_kg'],'reference_fuel_kg':reference['fuel_kg'],'summed_wear_increment':j['wear'],
 'temperature_range_c':[min(w['tread'] for r in a for w in r['wheels']),max(w['tread'] for r in a for w in r['wheels'])],
 'mass_equation_residual':j['maximum_mass_equation_residual'],'closure':j['periodicity'],'solver':j['solver'],'replay':j['replay_validation']}
main={};laps={}
for track in ['technical_test_circuit','spa-francorchamps']:
 for vehicle in ['mclaren-p1','mcl36']:
  p=DATA/f'{track}-{vehicle}-fastest.json'
  if not p.exists():p=DATA/f'study/{vehicle}-fastest.json'
  j=read(p);r=read(p.with_name(p.stem+'-reference.json'));main[f'{track}/{vehicle}']=details(j,r);laps[(track,vehicle)]=(j,r)
summary={'scope':'restricted native path-and-speed policy optimization; no global or full-state optimality claim','primary':main,'validation':read(DATA/'final-replay-validation.json'),'render':read(DATA/'render-performance.json')}
a= laps[('spa-francorchamps','mclaren-p1')][0];b=laps[('spa-francorchamps','mcl36')][0];s=np.linspace(max(a['samples'][0]['s'],b['samples'][0]['s']),min(a['samples'][-1]['s'],b['samples'][-1]['s']),2000)
summary['spa_vehicle_line_difference']={'rms_m':float(np.sqrt(np.mean((interp(a,s,'lateral')-interp(b,s,'lateral'))**2))),'maximum_m':float(np.max(np.abs(interp(a,s,'lateral')-interp(b,s,'lateral'))))}
(DATA/'final-summary.json').write_text(json.dumps(summary,indent=2)+'\n')
plt.rcParams.update({'font.size':9,'axes.grid':True,'grid.alpha':.2})
fig,axes=plt.subplots(3,1,figsize=(11,8),sharex=True)
for vehicle,color in [('mclaren-p1','#d96a20'),('mcl36','#168da8')]:
 j,r=laps[('spa-francorchamps',vehicle)];rows=j['samples'];s=vector(rows,'s');axes[0].plot(s,np.linalg.norm(vector(rows,'velocity'),axis=1)*3.6,label=vehicle,color=color);axes[1].plot(s,vector(rows,'lateral'),color=color);axes[2].plot(s,vector(rows,'time')-interp(r,s,'time'),color=color)
axes[0].legend();axes[0].set_ylabel('Speed (km/h)');axes[1].set_ylabel('Offset from center (m)');axes[2].set_ylabel('Policy − reference (s)');axes[2].set_xlabel('Spa progress (m)');fig.suptitle('Approximate native models — locally improved 4-node policies, 2 ms integration');fig.tight_layout();fig.savefig(DOC.with_name('m6-spa-comparison.png'),dpi=160);plt.close(fig)
pareto=[r for r in study if r['name'].startswith('p1-pareto') or r['name'] in ['mclaren-p1-fastest','mclaren-p1-fuel']]
fig,ax=plt.subplots(figsize=(8,4.5))
for i,r in enumerate(sorted(pareto,key=lambda r:r['weights'][5])):ax.scatter(r['fuel_kg'],r['lap_time_s'],color=plt.get_cmap('tab10')(i),marker=['o','s','^','D','x'][i],s=65,label=f"Fuel weight {r['weights'][5]:g}")
ax.legend(loc='center right',title='Normalized time/fuel objective');ax.margins(.08)
ax.set(xlabel='Fuel used (kg)',ylabel='Lap time (s)',title='P1 technical circuit: sampled time/fuel trade-offs\nNot a proven Pareto frontier');fig.tight_layout();fig.savefig(DOC.with_name('m6-time-fuel-tradeoff.png'),dpi=160);plt.close(fig)
lines=['# Milestone 6 dynamics — implementation and final validation','',
'Validated on 2026-09-20, Apple M2 Pro. This report follows the [expanded dynamics request](../architecture/milestone-6-dynamics-request.txt). The old planar simulator, reference controller and CasADi/IPOPT collocation optimizer remain available. Their results are not reused as new-model validation.','',
'**Status:** the native contact model, vehicle/resource models, interactive driving, seven objective presets, force audit, Spa comparison UI and reproducible studies are implemented. The new optimizer is a restricted path-and-speed policy search. The requested unrestricted state/control optimal-control problem and robust open-loop Spa control replay are **not complete**. Four-node Spa results are useful validated feedback policies, not credible minimum-time limits of either real car.','',
'## Open and reproduce','',
'The pinned optimizer/report environment requires Python 3.12+ (tested 3.14). Native build: C++20/CMake 3.24+. Dashboard: Node 22.12+ and WebGL2.','',
'```sh','cmake -S . -B build -DCMAKE_BUILD_TYPE=Release','cmake --build build -j 6','ctest --test-dir build --output-on-failure','python3 -m venv .cache/optimizer-venv','.cache/optimizer-venv/bin/pip install -r tools/dynamics/requirements.txt','python3 tools/dynamics/server.py','# In a second terminal:','npm --prefix apps/dashboard ci','npm --prefix apps/dashboard run dev','```','',
'Open **http://127.0.0.1:5173/?drive**. Choose P1/MCL36 and Spa/Monza/Silverstone/Suzuka/Technical Test Circuit. `/` preserves the previous standalone replay application; `/?contact` opens contact fixtures. Source car packages and processed GLBs remain ignored: use [asset reproduction](../../assets/cars/README.md) on a fresh checkout. Local licensed assets are present in this workspace.','',
'```sh','.cache/optimizer-venv/bin/python tools/dynamics/prepare_track.py','.cache/optimizer-venv/bin/python tools/dynamics/optimize.py --vehicle mclaren-p1 --track technical_test_circuit','.cache/optimizer-venv/bin/python tools/dynamics/optimize.py --vehicle mclaren-p1 --track spa-francorchamps','.cache/optimizer-venv/bin/python tools/dynamics/optimize.py --vehicle mcl36 --track spa-francorchamps','.cache/optimizer-venv/bin/python tools/dynamics/study.py','.cache/optimizer-venv/bin/python tools/dynamics/sensitivity.py','.cache/optimizer-venv/bin/python tools/dynamics/revalidate.py',
'.cache/optimizer-venv/bin/python tools/dynamics/revalidate.py data/generated/dynamics/study/*.json --output data/generated/dynamics/study/replay-audit.json',
'python3 tools/dynamics/validate_driving.py','.cache/optimizer-venv/bin/python tools/dynamics/report.py','```','',
'Dense solver traces are ignored; compact summaries and reports are versionable. A clean checkout must run the commands to generate dynamic ghosts. The UI explicitly disables unavailable replay choices. Optimization is offline; IMPROVE starts the same script, reports progress and loads only an accepted result. No cloud service is required.','',
'## 1–2. Contact and airborne model','',
'The new C++ model integrates world position/velocity, quaternion attitude/angular rate and four body-axis unsprung sliders through a coupled 10×10 mass matrix. Independent road queries supply tire planes/materials. Unilateral compliant normal force drives the existing combined-force brush law: an airborne wheel has exactly zero Fx/Fy/Fz. There is no render grounding override. See [equations](../physics/contact-3d-model.md) and [30-run contact validation](milestone-6-dynamics-phase-a.md).','',
'Synthetic no-aero crest: no full flight at 12/20 m/s entry; 0.640 s full-airborne time at 28 m/s and 2.018 s at 40 m/s, including rebound. At 40 m/s, 2/1/0.5 ms give 2.0180/2.0180/2.0175 s. Extreme landing compression is outside credible tire/suspension calibration; this is a numerical/contact stress test. Accepted Spa policies have zero full-airborne duration. This does not establish whether a real car becomes airborne at any real Spa crest.','',
'## 3–5. Vehicle calibration, provenance and aero','',
'P1 headline anchors come from [McLaren](https://cars.mclaren.com/us_en/legacy/mclaren-p1); F1 architecture from [MCL36 specifications](https://www.mclaren.com/racing/formula-1/2022/car-launch/mclaren-mcl36-technical-specification/) and the versioned FIA rules linked in [F1 provenance](../vehicles/mcl36-approx.md). Every dynamic parameter has a source class. Mass/power anchors do not make estimated tire, inertia, suspension or aero maps official.','',
'| P1 metric | Published anchor | Fixed-mass mechanical bench | Difference |','|---|---:|---:|---:|']
cal=read(DATA/'phase-b-validation.json')['p1']['0.002']
for label,key,target,unit in [('0–100','zero_to_100_s',2.8,'s'),('0–200','zero_to_200_s',6.8,'s'),('100–0','brake_100_m',30,'m'),('200–0','brake_200_m',116,'m'),('Top speed','top_speed_kph',350,'km/h')]:lines.append(f'| {label} | {target:g} {unit} | {cal[key]:.4f} {unit} | {cal[key]-target:+.4f} {unit} |')
lines += ['',
'Calibration uses 13 least-squares iterations / 65 native calls, about 35.4 s. Resources are disabled for this controlled mechanical fit. The fitted road CdA reaches its bound: the headline fit is underidentified, not independent whole-vehicle validation. P1 uses a soft 350 km/h governor; MCL36 has none. See [calibration protocol](milestone-6-dynamics-phase-b-c.md).','',
'P1 mass anchor 1490 kg includes the configured 30 kg reference fuel; MCL36 795 kg excludes fuel. Seven versus eight gear ratios and RPM/shift states affect wheel power. At 70 m/s in the fixed bench, P1 high-aero downforce is capped at 5.884 kN. MCL36 predicts 20.818 kN: estimated ride-height-sensitive floor plus wings. DRS changes drag 3.602→2.881 kN and downforce 20.818→18.837 kN, shifting front fraction 45→49.7%. These are model predictions, not measurements.','',
'## 6–9. Fuel, hybrid, thermal and wear','',
'Fuel flow follows delivered positive tire work and estimated engine efficiency, with F1 min(100, 0.009 RPM + 5.5) kg/h ceiling. Fuel changes sprung mass at its CG; tank CG/inertia migration is omitted. F1 MGU-K is bounded by 120 kW, 4 MJ deployment and 2 MJ recovery per lap. Rear braking recovery replaces existing braking work; it does not add free braking force. No MGU-H model. P1 capacity is an explicitly estimated 4.7 kWh; no P1 recovery is claimed.','',
'Each tire integrates tread/carcass temperature and wear from slip/deformation work, air cooling and road conduction. Temperature/wear scale the existing force law. Thermal coefficients and wear law are generic estimates. No pressure, physical wheel-spin state, longitudinal-slip heat, ABS, TC or detailed differential. [Resource equations, conservation tests and approximations](../physics/resources.md).','',
'## 10–13. Driving, input, ghosts and delta','',
'A loopback Python HTTP host owns one native C++ simulator. Physics is fixed 500 Hz, snapshots 100 Hz, browser commands/polls 25 Hz; rendering does not advance physics. The input watchdog releases controls after 350 ms. W/S/A/D and arrows use rate-limited steering; Gamepad API uses analog steering/triggers with configurable deadzone/saturation/rate. Authentic has no hidden stabilizer; Assisted applies an explicitly named steering envelope.','',
'Time Ghost samples accepted replay at player elapsed time. Distance Reference samples its monotonic s map. Live delta is t_player − t_policy(s); comparison delta is t_policy(s) − t_reference(s). Analysis sectors are equal thirds, not official timing loops. Map, trace and slider clicks seek one replay cursor. Reset reconstructs native physical/resource state. Vehicles can leave asphalt onto the native lower-grip grass surface without teleporting.','',
'## 14–15. Solver and constraints','',
'SciPy PRIMA COBYLA solves native single shooting with periodic Catmull–Rom lateral-offset and speed-scale nodes; no generic solver or alternate optimistic tire model was written. Full physical/resource states are integrated, but are not independent optimization variables. A completed native reference lap supplies the identical initial state for all candidates. Offsets are bounded ±3 m; speed scales 0.7–1.45 of reference. The start node is fixed. Minimum-time mode minimizes elapsed time. Other normalized terms cover path length, minimum clearance, front/rear utilization balance, body tilt/rates, fuel and wear; custom weights sum to one. Fuel/wear obey a 115% reference-time ceiling.','',
'Clearance includes vehicle half-width + 0.25 m. It is not a yaw-dependent full-body envelope. Mechanical closure tolerances: 0.5 m/s body speed, 0.03 rad heading, 0.05 rad/s angular rate, 10 mm suspension. Fuel/temperature/wear need not be periodic. There are no collocation defects in this formulation; the recorded mass-equation residual measures a different quantity. [Full formulation](../physics/dynamic-optimization.md).','',
'Acceptance requires bounded feasible trajectory, converged solver and independent half-step feedback replay within 0.5 m position, 0.5 m/s speed and 0.03 rad yaw. Recorded-control open-loop replay is also evaluated; it can diverge materially on Spa. Such policies are accepted only as feedback policies, **not validated open-loop optimal-control solutions**. Candidate selection rejects bound-violating COBYLA exploratory points. A faster P1 Spa candidate (223.660 s) failed the yaw gate; 223.940 s passed. The invalid F1 exploratory result 210.380 s was replaced by bounded 212.760 s. Audits are retained.','',
'## 16–18. Vehicle-specific lines, force audit and lap results','',
'| Track / model | Reference s | Accepted policy s | Improvement s | Solver evaluations | Solver wall s |','|---|---:|---:|---:|---:|---:|']
for key,r in main.items():lines.append(f"| {key} | {r['reference_lap_time_s']:.3f} | {r['lap_time_s']:.3f} | {r['improvement_s']:.3f} | {r['solver']['evaluations']} | {r['solver']['wall_s']:.2f} |")
lines+=['','Solver wall times include the initial final-candidate replay work, but later audit/selection reruns are additional. COBYLA reports evaluations rather than a separate iteration count. Four policy nodes give six variables and 16 reported inequalities including bounds. Peak solver memory was not measured.','',
'| Model on Spa | Peak km/h | Peak braking g | Peak lateral g | Peak downforce kN | Fuel kg | Mean tire utilization ref → policy | Max offset change vs reference m | Largest 100 m gain |','|---|---:|---:|---:|---:|---:|---|---:|---|']
for vehicle in ['mclaren-p1','mcl36']:
 r=main[f'spa-francorchamps/{vehicle}'];g=r['largest_100m_gain'];lines.append(f"| {vehicle} | {r['peak_speed_kph']:.2f} | {r['peak_braking_g']:.3f} | {r['peak_abs_lateral_g']:.3f} | {r['peak_downforce_n']/1000:.3f} | {r['fuel_kg']:.4f} | {r['reference_mean_tire_utilization']:.3f} → {r['mean_tire_utilization']:.3f} | {r['maximum_offset_difference_m']:.3f} | {g['start_m']:.1f}–{g['end_m']:.1f} m: {g['gain_s']:.3f} s |")
d=summary['spa_vehicle_line_difference'];lines+=['',f"P1 versus F1 offset difference: RMS {d['rms_m']:.3f} m, maximum {d['maximum_m']:.3f} m over common coverage. Lower F1 mass and larger speed-dependent aero/friction capacity change braking, speed and line response. Four coarse nodes do not resolve every apex; these laps remain far from real-car performance limits. Tire utilization peaks at 1 for both models; requested demand can exceed 1 while actual force remains saturated.",'','![Spa model comparison](m6-spa-comparison.png)','',
'Force audit: steady ±0.035 rad steering at 15 m/s produces mirrored ±0.20930 rad/s yaw, radius 71.3937 m. Rear left/right lateral forces are 1323.59/1327.29 N inward in the left turn. World force reconstruction error is zero in the audit. UI arrows originate at actual contact patches and represent road-on-vehicle force. Tire Local/Body/World changes inspected components, not world arrow direction. [Machine audit](../../data/generated/dynamics/force-audit.json).','',
'| Replay case | Max position m | Max speed m/s | Max yaw rad | Minimum clearance m | Closure normalized max |','|---|---:|---:|---:|---:|---:|']
for r in summary['validation']:lines.append(f"| {r['track']} / {r['vehicle']} | {r['position_max_m']:.6f} | {r['speed_max_mps']:.6f} | {r['yaw_max_rad']:.6f} | {r['minimum_clearance_m']:.4f} | {r['periodicity']['normalized_max']:.4f} |")
lines+=['','All four final replays complete: zero track/control violation, tire-force violation ≤4.45e−16 normalized, zero nonzero airborne tire forces. The largest native mass-equation residual is below 1e−11. Recorded lap endpoints are sampled at 20 ms; near-zero reported lap-time difference does not imply sub-millisecond accuracy. See [replay audit](../../data/generated/dynamics/final-replay-validation.json).','',
'### Objective, grid and initialization study','',
'| Case | Objective J | Time s | Clearance m | Closure ratio | Evaluations | Wall s | Accepted |','|---|---:|---:|---:|---:|---:|---:|---|']
for r in study:lines.append(f"| {r['name']} | {r['objective_value']:.6f} | {r['lap_time_s']:.3f} | {r['minimum_clearance_m']:.3f} | {r['periodicity']['normalized_max']:.4f} | {r['solver']['evaluations']} | {r['solver']['wall_s']:.2f} | {r['accepted']} |")
lines+=['','All listed solver terminations reach their configured trust-region tolerance (study 0.04, primary 0.02). Objective values use different weights/scales and must not be ranked across presets. P1 4/6/8-node study lap times improve 41.60→40.68→40.30 s; this is **not sufficient to establish grid convergence**. Left/right initial guesses produce different local policies. All 21 final study replays pass: worst position error 0.4063 m, worst yaw error 0.01953 rad. [Per-case replay constraints](../../data/generated/dynamics/study/replay-audit.json); full constraints and normalized components are in [study summary](../../data/generated/dynamics/study/summary.json).','',
'Grip/mass sensitivity: P1 μ×0.85 43.24 s; μ×1.15 coarse 40.02 s fails replay position (0.518 m), refined 1 ms solve 39.98 s passes at 0.5 ms. Mass×0.9 gives 41.36 s; mass×1.1 gives 42.04 s. Original configs are unchanged. [All attempts](../../data/generated/dynamics/sensitivity/summary.json).','',
'![Time and fuel trade-offs](m6-time-fuel-tradeoff.png)','',
'## 19–20. UI, assets, geometry and environment','',
'The new DRIVE workspace uses a restrained header, left session/delta column, dominant chase viewport, map/status/aero/G panels and bottom stacked telemetry, suspension/tire inspection and driver/solver controls. Gear, RPM, temperature, fuel and energy come from the new model; no pressure is shown. Tire inspection includes actual normalized force circle, temperature/wear/Fy history and force frames. Comparison shows both spatial traces and synchronized cursor.','',
'![Target-state comparison](../screenshots/m6-target-comparison.png)','',
'Manual comparison with `docs/design/apexlab-target-ui.png`: major panel hierarchy, dark palette, density, orange P1, wooded elevated road and stacked traces now align much more closely. The road still lacks target-level surface art; billboard repetition and simple barriers are visible. The supplied GLB silhouette is retained. This is not a AAA or surveyed recreation. Further art/performance work remains.','',
'P1 source 241,320 triangles / 16,772,489 bytes → 228,936 / 11,751,168 bytes; estimated decoded textures 69,847,873 bytes. F1 1,050,630 triangles / 67,774,007 bytes → same triangle count / 29,951,804 bytes; textures 39,146,834 bytes. Lossless Meshopt buffers, wheel pivots and separate visual/physics configs remain. CC-BY authors and source links are in [asset docs](../../assets/cars/README.md). No manual Sketchfab download is needed in this workspace; a clean checkout needs legally acquired source packages.','',
'OSM import retains explicit course topology/selection, WGS84 local ENU metres and unscaled geometry; all four real circuits remain selectable. Spa uses Copernicus 30 m DSM, never laser-scan claims. Original import 7014.887 m vs 7004 m reference (+0.15544%). Native dynamic Spa has a separately named 35 m Gaussian height filter; XY unchanged, RMS height change 0.4981 m/max 3.5071 m, height range 102.123 m. The original comparison is retained as source_length_validation; the production C++ spline after dynamic filtering measures 7010.032747 m, +6.032747 m (+0.08613%) against 7004 m. Widths are estimated; banking zero.','',
'Terrain remains bounded circuit-local. Physics kerb height is exported to the renderer; locations are illustrative, not mapped Spa kerbs. Barriers/fences/forest are visual only. Local Poly Haven CC0 HDR/surface maps total 3,821,179 bytes with manifest. Trees are instanced full-cluster alpha billboards in one draw call. The generated decorative atlas is `apps/dashboard/public/assets/environment/forest-atlas-generated.png`; its exact imagegen prompt and caveats are in [foliage provenance](../../assets/external/polyhaven-environment/generated-foliage.md). It is not an external photograph or scientific source.','',
'## 21. Rendering performance','']
r=summary['render'];lines += [f"Headless Chromium, development Apple M2 Pro, 1672×944: mean frame {r['mean']:.2f} ms; p95 {r['p95']:.2f} ms; {r['calls']} draw calls; {r['triangles']:,} rendered triangles; {r['textures']} textures. Seek-to-two-frame measurements {r['seek_to_two_frames_ms']} ms. This is below the desired 60 fps. Figures include the measured final test view, not a controlled manual display benchmark.",'',
f"P1 GLB response duration {r.get('assetResponseMs',0):.1f} ms; first rendered car {r.get('carFirstRenderedMs',0):.1f} ms after scene setup. The latter includes shared Suspense dependencies, decoding and first rendering, not isolated GLB decoding. Environment resource response timings: {r.get('environmentResponses',[])}. Resource timings include local transfer/cache behavior; they are not disk cold-cache or isolated environment GPU-upload timings. Decoded texture estimates exclude shadow maps/framebuffers. Native Release real-time budget passes; UBSan timings are not compared with Release.",'',
'## 22. Verification and screenshots','',
'- Release CTest: 17/17 passed, including preserved models, native input/shooting, contact, resources and force audit.','- UBSan: all 17 correctness tests passed across full run and focused rerun. The initial native-driver failure was a Release-only wall-clock assertion mistakenly applied to instrumentation; it is now limited to Release. The tests explicitly load the instrumented shared library.','- Frontend: 52 unit tests and production build passed. Full 23-test Playwright suite passed; final changed DRIVE interactions also rerun.','- Browser checks include keyboard/gamepad mock, vehicle switch/reset, replay seek, force-frame inspection, objective controls and no page errors. Hardware gamepad use has not been manually verified.','- Native driving smoke checks pass for both cars on all five circuits. A 20 s manual-input run reaches grass at 42.804 m offset without teleporting and resets to time zero. [Driving audit](../../data/generated/dynamics/driving-validation.json). Contact fixtures test grass, curb and crest departure/landing. The same native road/contact core runs interactively; destructive high-speed live-session handling is not an OEM-validated behavior.','',
'Screenshots: `m6-target-comparison.png`, `m6-engineering-overlay.png`, `m6-reference-optimized.png`, `m6-telemetry-comparison.png`, `m6-track-map-comparison.png`, `m6-optimization-panel.png`, `m6-drive-p1.png`, `m6-drive-f1.png`, `m6-drive-forces.png`, `m6-contact-airborne.png`, `m6-contact-curb.png` under `docs/screenshots/`.','',
'## 23. Remaining approximations and next work','',
'The highest-priority next step is full-state multiple shooting/collocation with direct steering/power/ERS/DRS decisions, stricter periodicity, fine-grid convergence and robust independent control replay. The present feedback-policy results must keep their scoped label. Follow with better road elevation/width measurements, measured tire/aero identification, nonlinear impact/bottoming, yaw-dependent body envelope and render profiling/LOD. Extreme-impact credibility, detailed suspension geometry, wheel angular dynamics and thermal parameter identification remain open. Multiplayer and additional ABS/TC systems were not started.','',
'This report therefore records implemented phases and measured limits, rather than declaring every requested optimal-control and visual-quality completion criterion fulfilled.']
DOC.write_text('\n'.join(lines)+'\n')
print(DOC)
