"""Repository-authored deterministic PBR texture tiles; all dimensions in runtime UV metres."""

from pathlib import Path
import numpy as np
from PIL import Image

out = Path(__file__).resolve().parents[2] / "apps/dashboard/public/assets/surfaces"
out.mkdir(parents=True, exist_ok=True)
rng = np.random.default_rng(5541)
size = 512
for name, base, grain in [
    ("asphalt", (85, 88, 88), 12),
    ("grass", (59, 76, 39), 20),
    ("gravel", (125, 116, 99), 26),
]:
    fine = rng.normal(0, 1, (size, size))
    coarse = (
        np.asarray(
            Image.fromarray(rng.integers(0, 255, (32, 32), dtype=np.uint8)).resize(
                (size, size), Image.Resampling.BICUBIC
            ),
            dtype=float,
        )
        / 255
        - 0.5
    )
    height = 0.6 * fine + 0.4 * coarse
    color = np.clip(
        np.array(base)[None, None, :] + height[:, :, None] * grain, 0, 255
    ).astype(np.uint8)
    Image.fromarray(color).save(out / f"{name}-color.png")
    Image.fromarray(np.clip(220 + height * 10, 0, 255).astype(np.uint8)).save(
        out / f"{name}-roughness.png"
    )
    dx = (np.roll(height, 1, 1) - np.roll(height, -1, 1)) * 0.07
    dy = (np.roll(height, 1, 0) - np.roll(height, -1, 0)) * 0.07
    n = np.stack([dx, dy, np.ones_like(dx)], axis=2)
    n /= np.linalg.norm(n, axis=2, keepdims=True)
    Image.fromarray(np.clip((n * 0.5 + 0.5) * 255, 0, 255).astype(np.uint8)).save(
        out / f"{name}-normal.png"
    )
(out / "README.md").write_text(
    "Repository-authored seeded aggregate/vegetation textures, generated by tools/assets/create_surface_textures.py. No external imagery. Asphalt tile repeats every 4 metres; micro-normal variation is visual only. Not surveyed surface roughness.\n"
)
